### ISSUE TITLE
Can it support other LLM like claude-2?

### ISSUE THREAD

**Issue by QIanGua** [Cobular/raycast-openinterpreter#1]
It has already been supported by openinterpreter, e.g. `interpreter --model claude-2`

**Comment by Cobular** [comment]
Yeah, trivially! I'll add that soon

**Comment by Cobular** [comment]
@QIanGua can you test this for me plz? I don't have an anthropic acct setup

**Comment by QIanGua** [comment]
I am testing this.  But It seems it can't find the python path in `python_handlers.ts` line 236.  

My minconda's python path is `~/miniconda3/bin/python`

![CleanShot 2023-10-15 at 10 58 21@2x](https://github.com/Cobular/raycast-openinterpreter/assets/7362290/a797a55d-c2b6-4f0e-a4ae-53a58e5e897d)

**Comment by Cobular** [comment]
Oh shoot - it's supposed to ship with its own venv. I'll investigate tomorrow

**Comment by Cobular** [comment]
Ok, I think there was an issue with the install command and the way it setup the virtual environment.

0. If you have an openinterpeter extention already created, uninstall it with the following
![image](https://github.com/Cobular/raycast-openinterpreter/assets/22972550/efa97e05-f0a3-4a9b-a17d-3c6a9107c275)

1. Download and setup [Raycast](https://www.raycast.com/)
2. Clone this repo down (`git clone https://github.com/Cobular/raycast-openinterpreter.git`)
3. `npm i && npm run dev`
4. It's now there in your Raycast! Once you kill that running command, you'll be good to go. 

Essentially, skip the creation of a template thing - I think that was a bad idea.

----

Please let me know if that worked. If not, send me a screenshot of the assets directory of the project AFTER you `npm run dev` it. To do so, open a new terminal tab and run `ls ~/.config/raycast/extensions/openinterpreter/assets/` while `npm run dev` is running. Thank you!

**Comment by QIanGua** [comment]
@Cobular I reinstalled the extension from latest pull, but it reports the following error for both my OpenAI (with personal openai_api_base) and Claude: "Got garbage from the sub-process: SyntaxError: Unexpected token A in JSON at position 0." Additionally, it doesn't respond when I try to set the dark theme. 🤣
![CleanShot 2023-10-17 at 10 41 50@2x](https://github.com/Cobular/raycast-openinterpreter/assets/7362290/65a51b86-dc71-41d6-8377-a72c56c74a5d)

**Comment by Cobular** [comment]
Hey! Sorry I've been busy with homework these last few days 😵‍💫 I think I have a fix - can you try this? https://github.com/Cobular/raycast-openinterpreter/issues/4#issuecomment-1769790558
