### ISSUE TITLE
Add support for custom openai_api_base

### ISSUE THREAD

**Issue by QIanGua** [Cobular/raycast-openinterpreter#2]
I have an OpenAI Key linked to a specific OpenAI API Base, like https://openaiXXX.cloud/v1, instead of the default base, https://api.openai.com/v1. It appears that openinterpreter, available at https://github.com/KillianLucas/open-interpreter/pull/64, has added support for this (I can use it in terminal successfully). Perhaps we can include an optional preference for OPENAI_API_BASE.

**Comment by Cobular** [comment]
Yep, that'll be easy!

**Comment by Cobular** [comment]
Fixed in latest commit, added new feature to select
