### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JohnnWi** [Cobular/raycast-openinterpreter#3]
hey, i follow the guide but i have this error 
<img width="1512" alt="image" src="https://github.com/Cobular/raycast-openinterpreter/assets/129292024/fec3447b-47bb-40fa-9253-1132b7cd6d9a">

**Comment by Cobular** [comment]
Ok, I think this wasn't the best set of install instructions. Can you do this instead?

0. If you have an openinterpeter extention already created, uninstall it with the following
![image](https://github.com/Cobular/raycast-openinterpreter/assets/22972550/efa97e05-f0a3-4a9b-a17d-3c6a9107c275)

1. Download and setup [Raycast](https://www.raycast.com/)
2. Clone this repo down (`git clone https://github.com/Cobular/raycast-openinterpreter.git`)
3. `npm i && npm run dev`
4. It's now there in your Raycast! Once you kill that running command, you'll be good to go. 

Essentially, skip the creation of a template extention - I think that was a bad idea.

----

Please let me know if that worked. If not, send me a screenshot of the assets directory of the project AFTER you `npm run dev` it. To do so, open a new terminal tab and run `ls ~/.config/raycast/extensions/openinterpreter/assets/` while `npm run dev` is running. Thank you!

**Comment by jpaulgale** [comment]
here is the results of npm i && npm run dev

```
added 190 packages, and audited 191 packages in 12s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> dev
> ray develop

info  -  generated extension's TypeScript definitions
info  -  entry points [src/index.tsx]
failed reading file info (stat assets/venv/bin/python: no such file or directory)
```


<img width="564" alt="image" src="https://github.com/Cobular/raycast-openinterpreter/assets/14095721/1b3276bb-b988-49e4-aee3-1ab2d96d9fa2">

here's that directory, in 
<img width="445" alt="image" src="https://github.com/Cobular/raycast-openinterpreter/assets/14095721/64015df0-fed9-4ec9-8b63-118d703ca8a3">

<img width="713" alt="image" src="https://github.com/Cobular/raycast-openinterpreter/assets/14095721/0f998885-6bd3-4f09-adea-0c93a94c11e5">

**Comment by Cobular** [comment]
Ok great. It didn't seem to get far enough along - can you wait a few seconds before opening the command? You should see the following before you try to start it:
```
❯ pnpm run dev                                             

> openinterpreter@ dev /Users/cobular/Documents/RaycastExtensions/openinterperter
> ray develop

info  -  generated extension's TypeScript definitions
info  -  entry points [src/index.tsx]
ready -  built extension successfully
12:00:00.015 /Users/cobular/.config/raycast/extensions/openinterpreter/assets/.bashrc
12:00:00.015 {
  OPENAI_API_KEY: '<API_KEY>',
  MODEL: 'gpt-3.5-turbo'
}
12:00:00.015 {}
12:00:00.016 Got garbage from the sub-process: SyntaxError: Unexpected token A in JSON at position 0 
 
Activating virtual environment
12:00:00.017 Got garbage from the sub-process: SyntaxError: Unexpected token / in JSON at position 0 
 /Users/cobular/Documents/RaycastExtensions/openinterperter/assets/venv/bin/python
12:00:00.511 Timeout reached, debouncing. Inputs: 0
12:00:00.726 Got garbage from the sub-process: SyntaxError: Unexpected token ▌ in JSON at position 0 
 
▌ A new version of Open Interpreter is available.
12:00:00.726 Got garbage from the sub-process: SyntaxError: Unexpected token ▌ in JSON at position 0 
 
▌ Please run: pip install --upgrade open-interpreter
12:00:00.727 Got garbage from the sub-process: SyntaxError: Unexpected token ─ in JSON at position 0 
 
────────────────────────────────────────────────────────────────────────────────
12:00:00.727 stderr: /Users/cobular/Documents/RaycastExtensions/openinterperter/assets/venv/bin/python
```

(note the **third log line with `ready`** - that means it has finished copying over the whole venv and everything). 

Does that happen? 

And after that happens, can you run `cat ~/.config/raycast/extensions/openinterpreter/assets/.bashrc`? That's what is responsible for loading up the venv.

**Comment by Cobular** [comment]
(also, please send me your current git commit `git rev-parse HEAD` and then pull to get my latest debug prints)

And thank you for your help testing this!

**Comment by Cobular** [comment]
Can I getcha to try this? https://github.com/Cobular/raycast-openinterpreter/issues/4#issuecomment-1769790558

**Comment by JohnnWi** [comment]
> Can I getcha to try this? [#4 (comment)](https://github.com/Cobular/raycast-openinterpreter/issues/4#issuecomment-1769790558)

hey man. i have try again and now work! thanks so much

**Comment by Cobular** [comment]
Hey I'm really glad! Please let me know of other issues - I'm (clearly) still ironing out the kinks, and if I don't see issues I can't fix em!

**Comment by JohnnWi** [comment]
sure, anyway then go and see on slack, we talked about your extension and one of the team said that there are still things to review. https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1697702633054039?thread_ts=1697702521.525859&cid=C02HEMAF2SJ

**Comment by Cobular** [comment]
Yep! Again I've been too busy to get around to this much, I'll try it this afternoon. I think it was just prettier tho.
