### ISSUE TITLE
Not getting responses

### ISSUE THREAD

**Issue by MikeBirdTech** [Cobular/raycast-openinterpreter#4]
Just went through the install process and got the chat interface loaded. After I sent my first message, there was no response and the console shows:

`Got garbage from the sub-process: SyntaxError: Unexpected token A in JSON at position 0 `

Running on a MacBook and entered a valid OpenAI API key

**Comment by Cobular** [comment]
Yep! There was a "works on my machine" issue. I believe I've fixed it - can you pull? I only have one mac to test on, so I'm relying on ya'll to help me get this working!

**Comment by JohnnWi** [comment]
I managed to try it, but I encountered some errors: 
1. every now and then it doesn't respond (it would be nice to have an error message): 
2. every now and then it asks to install additional files, but it tells me that it can't find the pip command (like when I want create a pdf file directly from etrminal and must download additional components). 
3. It would be nice if you added an option where you say how many tokens have been used. 
4. some times it asks me to confirm to install and I have to write "y", I would add the option to do it automatically without asking every time

**Comment by JohnnWi** [comment]
![image](https://github.com/Cobular/raycast-openinterpreter/assets/129292024/71fea8ec-760d-470d-93af-ee070da5d3f4) after run, i have this message, but work

**Comment by MikeBirdTech** [comment]
I pulled and am able to get a response 👍. I get the same error log as @JohnnWi but haven't noticed any issues because of it

**Comment by Cobular** [comment]
Yep that's normal - it shouldnt be an error - I'll have to change the warning system.
